name: copilot-deploy-backend

on:
  workflow_call:
    inputs:
      ARTIFACT_NAME:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      DEPLOYMENT_NAME:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
    outputs:
      backend-host:
        description: "Host to which backend is deployed"
        value: ${{jobs.webapi.outputs.backend-host}}

permissions:
  contents: read

jobs:
  webapi:
    environment: ${{inputs.ENVIRONMENT}}
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - { dotnet: "6.0", configuration: Release, os: windows-latest }
    # Map the job output to step output
    outputs:
      backend-host: ${{steps.app-name.outputs.backend-host}}

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{inputs.ARTIFACT_NAME}}
          path: "${{ github.workspace }}/${{inputs.ARTIFACT_NAME}}"

      - name: "Display downloaded content"
        run: dir -R
        working-directory: "${{ github.workspace }}/${{inputs.ARTIFACT_NAME}}"

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          enable-AzPSSession: false

      - name: Get app name
        id: app-name
        run: |
          $WEB_APP_NAME=$(az deployment group show --name ${{inputs.DEPLOYMENT_NAME}} --resource-group ${{vars.CC_DEPLOYMENT_GROUP_NAME}} --output json | ConvertFrom-JSON).properties.outputs.webapiName.value
          Write-Output "AZURE_WEBAPP_NAME=$WEB_APP_NAME" >> $env:GITHUB_ENV
          Write-Output "backend-host=$WEB_APP_NAME" >> $env:GITHUB_OUTPUT

      - name: Enable Run From Package
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az webapp config appsettings set --resource-group ${{vars.CC_DEPLOYMENT_GROUP_NAME}} --name ${{ env.AZURE_WEBAPP_NAME }} --settings WEBSITE_RUN_FROM_PACKAGE="1" -o none

      - name: "Deploy"
        run: |
          scripts\deploy\deploy-webapi.ps1 -DeploymentName ${{inputs.DEPLOYMENT_NAME}} -Subscription ${{secrets.AZURE_SUBSCRIPTION_ID}} -ResourceGroupName ${{vars.CC_DEPLOYMENT_GROUP_NAME}} -EnsureUriInAppRegistration -RegisterPluginCors
